CREATE DATABASE PRAC

USE PRAC

CREATE TABLE DEPARTMENT(
	ID INT PRIMARY KEY,
	NAME NVARCHAR(50) UNIQUE NOT NULL,
	LOCATION NVARCHAR(50),
)

CREATE TABLE DESIGNATION(
	ID INT PRIMARY KEY,
	TITLE NVARCHAR(50) UNIQUE NOT NULL,
	PAYSCALE NVARCHAR(50) NOT NULL,
	LEAVES INT	
)

CREATE TABLE EMPLOYEE(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NAME NVARCHAR(50) NOT NULL,
	AGE INT NOT NULL,
	SALARY INT,
	DOJ DATE,
	DES_KEY INT FOREIGN KEY REFERENCES DESIGNATION(ID),
	DEPT_KEY INT FOREIGN KEY REFERENCES DEPARTMENT(ID),
	PH_NO NVARCHAR(50),
	EMAIL NVARCHAR(50) 
)


INSERT INTO DESIGNATION VALUES(1, 'Junior Developer','BPS-17', 12)
INSERT INTO DESIGNATION VALUES(2, 'Senior Developer','BPS-18', 16)
INSERT INTO DESIGNATION VALUES(3, 'Team Lead','BPS-19', 20)
INSERT INTO DESIGNATION VALUES(4, 'Manager','BPS-20', 24)
INSERT INTO DESIGNATION VALUES(5, 'Executive Manager','BPS-21', 24)

INSERT INTO DEPARTMENT VALUES(1, 'DevOps','1st Floor')
INSERT INTO DEPARTMENT VALUES(2, 'Research','1st Floor')
INSERT INTO DEPARTMENT VALUES(3, 'Development','2nd Floor')
INSERT INTO DEPARTMENT VALUES(4, 'Support','3rd Floor')
INSERT INTO DEPARTMENT VALUES(5, 'Human Resource','3rd Floor')

INSERT INTO EMPLOYEE VALUES('Ali',23, 30000, '2019-12-01',1,3,'03341234567','ali@gmail.com')
INSERT INTO EMPLOYEE VALUES('Bilal',27, 60000, '2020-03-09',2,3,'03361234567','bilal_122@gmail.com')
INSERT INTO EMPLOYEE VALUES('Zubair',43, 250000, '2010-05-01',5,2,'03001234567','Zubair_gmail@hotmail.com')
INSERT INTO EMPLOYEE VALUES('Daniyal',30, 130000, '2017-04-25',3,1,'03021234567','dani@hotmail.com')
INSERT INTO EMPLOYEE VALUES('Mustafa',37, 220000, '2012-06-06',4,5,'03347654321','mustafa@outlook.com')

SELECT * FROM EMPLOYEE
SELECT * FROM DESIGNATION
SELECT * FROM DEPARTMENT
-- 1
SELECT * FROM EMPLOYEE WHERE PH_NO LIKE '0334%'
-- 2
UPDATE EMPLOYEE SET SALARY = SALARY+500 WHERE PH_NO LIKE '0336%'
-- 3
SELECT * FROM EMPLOYEE WHERE EMAIL LIKE '%@GMAIL%'
-- 4
SELECT EMAIL,REPLACE(EMAIL,'@','_') FROM EMPLOYEE
-- 5
UPDATE EMPLOYEE SET EMAIL=REPLACE(EMAIL,'@','_') FROM EMPLOYEE
-- 6
SELECT NAME,REPLACE(NAME,SUBSTRING(NAME,3,3 ),SUBSTRING(CONVERT(NVARCHAR,AGE),2,2 )) FROM EMPLOYEE
-- 7
SELECT NAME,DATEDIFF(YEAR,DOJ,GETDATE()) AS TOTALYEAR FROM EMPLOYEE
-- 8
SELECT NAME,DOJ AS HIREJOIN FROM EMPLOYEE WHERE DOJ >'2018-02-20'
-- 9
SELECT NAME,DES_KEY, SALARY,
CASE
	WHEN DES_KEY = 2 THEN SALARY*0.2
	WHEN DES_KEY = 3 THEN SALARY*0.3
	WHEN DES_KEY = 4 THEN SALARY*0.5
	WHEN DES_KEY!=2 OR DES_KEY!=3 OR DES_KEY!=5 THEN  SALARY*0.1
END	AS [FINAL RESULT]	
FROM EMPLOYEE
--10
SELECT NAME,CONCAT(SUBSTRING(NAME,1,2 ),SUBSTRING(CONVERT(NVARCHAR,AGE),1,2 )) AS COMEBINE FROM EMPLOYEE
